services:
    hj2-api-xml-rust:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3443:3443"
            - "8080:80"
        container_name: hj2-api-xml-rust
        restart: unless-stopped
        environment:
            - RUST_LOG=info
        volumes:
            - ./logs:/app/logs
        networks:
            - hj2-network

networks:
    hj2-network:
        driver: bridge
